WIP- #40 Integrate YOLOv8 pose model and corresponding save node
ChimeraPy/Pipelines pull request #41
Opened 2023-06-22 21:11 UTC by JaneWu423

Create a PoseNode to apply YOLO pose estimation model on streaming video. Created another SaveNode to handle results from the YOLO model and save it either in video (mp4) format or table (csv) format.

2023-06-23 17:06 UTC, JaneWu423 commented
#40

2023-06-30 14:29 UTC, umesh-timalsina requested changes
Good Work! The code is clean and understandable. However couple of meta questions:
1. How do you filter just people in the video, is it going to be filtered in the model inference step?
2. Some files seem redundant. Please check the review comments.

2023-06-30 14:29 UTC, umesh-timalsina commented on mmlapipe/pose/multi_save.py
> +"""
This needs to be inside the function docstring.

```py
def to_data_frame(results, frame_cnt, normalize=False):
"""Helper function to save results as json...."""
```

2023-06-30 14:29 UTC, umesh-timalsina commented on mmlapipe/pose/multi_pose_demo.json
> +}
No new line at the end of file. Additionally, this needs to be moved in `configs/` directory at the root of the repo

2023-06-30 14:29 UTC, umesh-timalsina commented on mmlapipe/pose/multi_save.py
> +        box = {"x1": row[0] / w, "y1": row[1] / h, "x2": row[2] / w, "y2": row[3] / h}
Instead of saving the box as a dictionary, can this be saved as a numpy array?

2023-06-30 14:29 UTC, umesh-timalsina commented on mmlapipe/pose/multi_save.py
> +            }
Same comment as above.

2023-07-05 18:52 UTC, JaneWu423 commented on mmlapipe/pose/pose_node.py
> +os.environ["YOLO_VERBOSE"] = "False"
Somehow moving it to setup function does not work, output still shows up in terminal, changed to setting verbose=False when calling self.model.

2023-07-05 18:53 UTC, JaneWu423 commented on mmlapipe/pose/pose_node.py
pose_node.py is redundant, it is used for only handling single video input. I have deleted it in new commits.

2023-07-05 19:24 UTC, JaneWu423 commented
> 

For 1, maybe adding a classes param, setting default to "person". Adapt the class idx code from yolo_node.py to achieve that. 
For 2, I have removed redundant files in new commits.

2023-07-21 18:06 UTC, umesh-timalsina commented
Good Work @JaneWu423. Cleaned up some files for formatting and logic. LGTM!

2023-07-21 18:06 UTC, merged